/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.first.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void hello() {
        App obj = new App();
        assertEquals(obj.getGreeting(), "Hello World!");
    }

    @Test
    void validate() {
        App obj = new App();
        assertEquals(obj.tables(12), 22);
    }
}
